### PR TITLE
Integration v1.0 - stich scripts together and minor bugfixes

### PR DESCRIPTION
**Pull request by adam-dej**
By accepting this PR, you agree with release of this as version 1.0. I would like to have LGTM from @AnotherKamila and from @Kuci

---

This change is [Reviewable](https://reviewable.io/reviews/trojsten/sysadmin-script-collection/13)

### CODE REVIEW

**Comment by lubo** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

_[repo-dirty-checker/repo-dirty-checker, line 28 [r1]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/13#-KDylbx27Xn-JITko1QC:-KDylbx3ITYqWDxBFsnv:545103161) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/898eee39600f21597ecb17aa91fa3b45a2ccd91c/repo-dirty-checker/repo-dirty-checker#L28)):_
Toto sa mi vobec nepaci. Nemali by sme tahat logiku do konfiguraku. Jednak mi to nedava zmysel a jednak to zabija portabilitu (parsovanie v inych jazykoch, ...).

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/13)_

**Comment by adam-dej** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

_[repo-dirty-checker/repo-dirty-checker, line 28 [r1]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/13#-KDylbx27Xn-JITko1QC:-KDynGFaRlQeB4fvM46-:-2143148347) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/898eee39600f21597ecb17aa91fa3b45a2ccd91c/repo-dirty-checker/repo-dirty-checker#L28)):_
Toz toto je urobene aj v properly, koli tomu ze nie je predvitatelne ako kde toto bude implementovane. Aj ked v pripade mailu to predvidatelne je, chcel som predist vsetkej byrokracii koli jednemu riadku ktora by nasledovala.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/13)_

**Comment by lubo** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

_[repo-dirty-checker/repo-dirty-checker, line 28 [r1]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/13#-KDylbx27Xn-JITko1QC:-KDypbW8OE7hVKp8Csjq:-497070355) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/898eee39600f21597ecb17aa91fa3b45a2ccd91c/repo-dirty-checker/repo-dirty-checker#L28)):_
Zasa, nie celkom sa citim byt zasvateny do toho, co to vsetko ma robit, ale moja predstava je zhruba takato: `send_mail()` nakrmime nejakymi datami, pricom tie data asi chceme nejako spracovat (napr. vlozit zoznam userov do tela spravy). To si myslim, ze bude pri kazdom maile rovnake. Druha vec je, ze kazdy z nas chce pouzivat nieco ine na odosielanie mailu (sendmail, postfix, ...). Moje idea je teda taka, ze spracovanie by sme mali naimplementovat v scripte a do kofniguraku pridat moznost `MAIL_COMMAND`, kde sa bude dat zadat command na odoslanie a nakrmit ho parametrami, ktore bude vkladat `send_mail()`.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/13)_

**Comment by AnotherKamila** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[repo-dirty-checker/repo-dirty-checker, line 28 [r1]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/13#-KDylbx27Xn-JITko1QC:-KDyr99K49Dd3xbsjN0d:793002504) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/898eee39600f21597ecb17aa91fa3b45a2ccd91c/repo-dirty-checker/repo-dirty-checker#L28)):_
Osobne si myslím, že `mail` funguje na všetkých rozumných systémoch (ak ti nefunguje, je to tvoj problém, nie problém tohoto skriptu). Použila by som `mail` s fixným subjectom a konfigurovateľnými adresami.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/13)_

**Comment by AnotherKamila** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[repo-dirty-checker/repo-dirty-checker, line 28 [r1]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/13#-KDylbx27Xn-JITko1QC:-KDyvXQFj5WI4P0J8mcx:694582956) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/898eee39600f21597ecb17aa91fa3b45a2ccd91c/repo-dirty-checker/repo-dirty-checker#L28)):_
Tak, ako hovorí @kuci , až na to, že by som tam nedávala ani MAIL_COMMAND a proste tam picla `mail -s whatever $SEND_MAIL_TO`.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/13)_

**Comment by lubo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[repo-dirty-checker/repo-dirty-checker, line 28 [r1]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/13#-KDylbx27Xn-JITko1QC:-KDyyCrjv8P6DS2yhZn4:-1830068275) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/898eee39600f21597ecb17aa91fa3b45a2ccd91c/repo-dirty-checker/repo-dirty-checker#L28)):_
Nechcem byt zly, ale "(ak ti nefunguje, je to tvoj problém, nie problém tohoto skriptu)" mi pride ako M$ statement. Ja som to chcel spravit trocha flexibilnejsie, ale nemusime to komplikovat ak netreba. Hovorim, vy musite vediet... Ak to chce byt`mail`, tak nech to je `mail`.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/13)_

**Comment by adam-dej** [comment]
Review status: 5 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

_[repo-dirty-checker/repo-dirty-checker, line 28 [r1]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/13#-KDylbx27Xn-JITko1QC:-KDzCKyHirqf31Z7D_yz:-499146009) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/898eee39600f21597ecb17aa91fa3b45a2ccd91c/repo-dirty-checker/repo-dirty-checker#L28)):_
Done.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/13)_

**Comment by lubo** [comment]
:lgtm:

---

Reviewed 5 of 7 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/13#-:-KDzDcR4MpAX1gTonCWr:1417088721)_

**Comment by AnotherKamila** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

_[repo-dirty-checker/repo-dirty-checker.conf, line 8 [r2]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/13#-KE25AUSoKOr_FVAUCPF:-KE25AUT2HSF9QF2LQQn:-1867040322) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/e1774de55c45cabbaecdfc98965adb00c395991b/repo-dirty-checker/repo-dirty-checker.conf#L8)):_
Tieto číselká sú podľa mňa málo, kľudne sa môže stať, že niekto na niečom robí zopár hodín a priveľa false positives aspoň mailom nechceme. Zmenila by som povedzme na 120.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/13#-:-KE24iYrMX9wVoyIurDC:1417088721)_

**Comment by adam-dej** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

_[repo-dirty-checker/repo-dirty-checker.conf, line 8 [r2]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/13#-KE25AUSoKOr_FVAUCPF:-KE28GOeaSGQYYJ5hvbp:-499146009) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/e1774de55c45cabbaecdfc98965adb00c395991b/repo-dirty-checker/repo-dirty-checker.conf#L8)):_
Done.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/13)_

**Comment by AnotherKamila** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/13)_

**Pull request merged**
