### PR TITLE
repo-dirty-checker: Add configuration file

### PR DESCRIPTION
**Pull request by lubo**
See #2 for details.

---

This change is [Review on Reviewable](https://reviewable.io/reviews/trojsten/sysadmin-script-collection/6)

### CODE REVIEW

**Comment by adam-dej** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_[repo-dirty-checker/repo-dirty-checker, line 10 [r1]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/6#-KClrwbN0F5XZjqzUzkp:-KClrwbOTrO2XpL-s9XT:139074277) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/8b448236f567e481cee42a7576a27970254c4c09/repo-dirty-checker/repo-dirty-checker#L10)):_
Cool, nevedel som že tento SW existuje. Možno ale chceš vysvetliť prečo tu ten komentár je nech ušetríš googlenie.

---

_[repo-dirty-checker/repo-dirty-checker, line 27 [r1]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/6#-KClsLZ99EE9NxVP7mkS:-KClsLZA1JcnyLOAEI2o:-1291414010) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/8b448236f567e481cee42a7576a27970254c4c09/repo-dirty-checker/repo-dirty-checker#L27)):_
Style guide:, lokálne premenné by mali byť definované ako lokálne.

---

_[repo-dirty-checker/repo-dirty-checker, line 52 [r1]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/6#-KClwYWGmLJ8HYbHAqHb:-KClwYWGmLJ8HYbHAqHc:1582480299) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/8b448236f567e481cee42a7576a27970254c4c09/repo-dirty-checker/repo-dirty-checker#L52)):_
Nebijú sa tu tie úvodzovky?

---

_[repo-dirty-checker/repo-dirty-checker, line 60 [r1]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/6#-KClx0IxiizAeukvHO9n:-KClx0IxiizAeukvHO9o:-512135721) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/8b448236f567e481cee42a7576a27970254c4c09/repo-dirty-checker/repo-dirty-checker#L60)):_
Nebolo by lepšie toto mať niekde vo fcii na začiatku (pri `init_run_file`, ...)?

---

_[repo-dirty-checker/repo-dirty-checker, line 70 [r1]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/6#-KClx6zcaqt5zHc1I0si:-KClx6zcaqt5zHc1I0sj:-173278137) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/8b448236f567e481cee42a7576a27970254c4c09/repo-dirty-checker/repo-dirty-checker#L70)):_
Tiež, nebolo by lepšie na toto mať fciu?

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/6)_

**Comment by lubo** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_[repo-dirty-checker/repo-dirty-checker, line 10 [r1]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/6#-KClrwbN0F5XZjqzUzkp:-KClzxGGE-ifog_2v1_d:461868197) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/8b448236f567e481cee42a7576a27970254c4c09/repo-dirty-checker/repo-dirty-checker#L10)):_
Naozaj treba vysvetlovat taketo veci ? Uplne rovnako mozeme potom vysvetlovat aj kazdy parameter, co vopchame do nejakeho commandu... Ak to tam chces, tak to pridam. Ak nie, tak mi usetris podla mna zbytocnu pracu.

---

_[repo-dirty-checker/repo-dirty-checker, line 27 [r1]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/6#-KClsLZ99EE9NxVP7mkS:-KCm-tjbIdrGFXoxg5tL:-378769262) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/8b448236f567e481cee42a7576a27970254c4c09/repo-dirty-checker/repo-dirty-checker#L27)):_
Mas pravdu, omilom som ich odstranil. Fixnem to.

---

_[repo-dirty-checker/repo-dirty-checker, line 52 [r1]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/6#-KClwYWGmLJ8HYbHAqHb:-KCm0qTvzO3cKDfjl_MY:-389192454) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/8b448236f567e481cee42a7576a27970254c4c09/repo-dirty-checker/repo-dirty-checker#L52)):_
AFAIK sa nebiju.

---

_[repo-dirty-checker/repo-dirty-checker, line 60 [r1]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/6#-KClx0IxiizAeukvHO9n:-KCm2Jc9Q7_oHFaWrnv2:-2020857934) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/8b448236f567e481cee42a7576a27970254c4c09/repo-dirty-checker/repo-dirty-checker#L60)):_
Ak to ma byt krajsie a dostupnejsie, tak ano. Inac zvyknem vytvarat funkcie len vtedy, ak sa dany kus kodu opakuje alebo je prilis komplikovany pre dany scope. V tomto pripade to nie je ani jeden z pripadov.

---

_[repo-dirty-checker/repo-dirty-checker, line 70 [r1]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/6#-KClx6zcaqt5zHc1I0si:-KCm2tlWa9Zgw6BPYfDv:1784500251) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/8b448236f567e481cee42a7576a27970254c4c09/repo-dirty-checker/repo-dirty-checker#L70)):_
Podobne ako riadok 60.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/6)_

**Comment by lubo** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_[repo-dirty-checker/repo-dirty-checker, line 27 [r1]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/6#-KClsLZ99EE9NxVP7mkS:-KCm49EirsE0J5q8aRms:1029515265) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/8b448236f567e481cee42a7576a27970254c4c09/repo-dirty-checker/repo-dirty-checker#L27)):_
Uz viem preco som ich odstranil. ShellCheck mi vypisoval: "In POSIX sh, 'local' is undefined. [SC2039]". Pozri si [SC2039](https://github.com/koalaman/shellcheck/wiki/SC2039) pre blizsie info.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/6)_

**Comment by adam-dej** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_[repo-dirty-checker/repo-dirty-checker, line 10 [r1]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/6#-KClrwbN0F5XZjqzUzkp:-KCm3woMXM4pe30oaarM:249262375) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/8b448236f567e481cee42a7576a27970254c4c09/repo-dirty-checker/repo-dirty-checker#L10)):_
Well, ja by som povedal že áno. Inak ho niekto neznalý môže odstrániť ("Veď je to len komentár"). Vysvetľovať každý param netreba, ale toto si možno vysvetlenie žiada (3 slová "kôli linteru - nemazať" stačia).

---

_[repo-dirty-checker/repo-dirty-checker, line 27 [r1]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/6#-KClsLZ99EE9NxVP7mkS:-KCm5PvarK_d9ULSspR9:-2138083839) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/8b448236f567e481cee42a7576a27970254c4c09/repo-dirty-checker/repo-dirty-checker#L27)):_
OK, potom ich nechceme. Offtopic: do README chceme napísať aký style guide používame a aké výnimky (a prečo) z neho robíme.

---

_[repo-dirty-checker/repo-dirty-checker, line 60 [r1]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/6#-KClx0IxiizAeukvHO9n:-KCm4Zl966I_lO0cZfse:-1218014503) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/8b448236f567e481cee42a7576a27970254c4c09/repo-dirty-checker/repo-dirty-checker#L60)):_
Ja si zas myslím, že toto je časť kódu ktorá sa môže customizovať častejšie než ostatné, a človeku čo by to chcel urobiť by jasne definovaný interface zjednodušil prácu. Prosím, urob ich.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/6)_

**Comment by lubo** [comment]
Review status: 1 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

_[repo-dirty-checker/repo-dirty-checker, line 27 [r1]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/6#-KClsLZ99EE9NxVP7mkS:-KCmCIInDUf9CvPmB9T-:1679605540) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/8b448236f567e481cee42a7576a27970254c4c09/repo-dirty-checker/repo-dirty-checker#L27)):_
**README:** Sprav issue.

---

_[repo-dirty-checker/repo-dirty-checker, line 60 [r1]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/6#-KClx0IxiizAeukvHO9n:-KCmCAMudUAfMD9jmm6r:-1421029113) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/8b448236f567e481cee42a7576a27970254c4c09/repo-dirty-checker/repo-dirty-checker#L60)):_
Done in 910e7cb.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/6)_

**Comment by lubo** [comment]
Review status: 1 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

_[repo-dirty-checker/repo-dirty-checker, line 10 [r1]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/6#-KClrwbN0F5XZjqzUzkp:-KCmF34K9TmooXlc2pCk:-599059424) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/8b448236f567e481cee42a7576a27970254c4c09/repo-dirty-checker/repo-dirty-checker#L10)):_
Ok, komentar pridany v 32429af.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/6)_

**Comment by adam-dej** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[repo-dirty-checker/repo-dirty-checker, line 80 [r2]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/6#-KCmFsBbNV-ck9pehuRC:-KCmFsBcL6RwS3v3NH-p:144412956) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/32429af4c09f01d542b3f93545946adee5949697/repo-dirty-checker/repo-dirty-checker#L80)):_
send_mail nechce brať parameter `"${dir}"`, rovnako ako `print_warning`? Nechcú obe mať ako parameter aj zoznam userov čo boli prihlásení keď bordel vznikol, nech sa to vie vypísať / poslať?

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/6)_

**Comment by lubo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[repo-dirty-checker/repo-dirty-checker, line 80 [r2]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/6#-KCmFsBbNV-ck9pehuRC:-KCmH-proYpakXIc6gz7:-648415238) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/32429af4c09f01d542b3f93545946adee5949697/repo-dirty-checker/repo-dirty-checker#L80)):_
Podla mna bude lepsie ked si budeme pridavat parametre podla potreby.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/6)_

**Comment by adam-dej** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[repo-dirty-checker/repo-dirty-checker, line 80 [r2]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/6#-KCmFsBbNV-ck9pehuRC:-KCoWK1dsR9jVdZlv8NB:-254510488) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/32429af4c09f01d542b3f93545946adee5949697/repo-dirty-checker/repo-dirty-checker#L80)):_
Pointa toho, aby toto bolo v inej funkcii je, aby sa človek nemusel hrabať v celom scripte keď chce meniť spôsob ktorým sa posiela mail, preto by bolo lepšie dať tam tie argumenty teraz a vo fcii hore napísať ktorý je čo.  Tiež nie je predpoklad že množina parametrov sa bude príliš meniť...

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/6)_

**Comment by lubo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[repo-dirty-checker/repo-dirty-checker, line 80 [r2]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/6#-KCmFsBbNV-ck9pehuRC:-KCoZPEjixkF7SINcySi:-1352269300) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/32429af4c09f01d542b3f93545946adee5949697/repo-dirty-checker/repo-dirty-checker#L80)):_
Dobre. Takze im dame `"${dir}"` a  zozname userov ? V akom formate chceme zoznam userov ? Delimitovany medzerami, nech sa da cez neho dobre iterovat ?

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/6)_

**Comment by adam-dej** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[repo-dirty-checker/repo-dirty-checker, line 80 [r2]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/6#-KCmFsBbNV-ck9pehuRC:-KCog11_-sYrw2CbhzTZ:1354385569) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/32429af4c09f01d542b3f93545946adee5949697/repo-dirty-checker/repo-dirty-checker#L80)):_
Ano, tak.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/6)_

**Comment by lubo** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_[repo-dirty-checker/repo-dirty-checker, line 80 [r2]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/6#-KCmFsBbNV-ck9pehuRC:-KCqb9S2QrE7W1TzmrPK:-688798977) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/32429af4c09f01d542b3f93545946adee5949697/repo-dirty-checker/repo-dirty-checker#L80)):_
Hotovo. Nakoniec som zoznam pouzivatelov nedelimitoval medzerou, newline by mal fungovat uplne rovnako.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/6)_

**Comment by adam-dej** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/6)_

**Pull request merged**
