### PR TITLE
Feature snapmanage

### PR DESCRIPTION
**Pull request by adam-dej**
Implement `zfs-manage-shell` which allows `zfs` command only.

---

This change is [Reviewable](https://reviewable.io/reviews/trojsten/sysadmin-script-collection/10)

### CODE REVIEW

**Comment by AnotherKamila** [comment]
Prípadne možno premenuj na proste `zfs-shell`, nie?

---

Reviewed 3 of 4 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_[a discussion](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/10#-KDiEyKgJhDdJzDTnPCY:-KDiEyKhRvtHwyVduUxY:-1984259608) (no related file):_
Podľa mňa by bolo milé môcť písať buď `zfs snapshot` alebo iba `snapshot`, ale nie je to nutné.

---

_[a discussion](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/10#-KDiFFr_SEQQAL3YLrMe:-KDiFFraV2-M78M5PtQX:739079664) (no related file):_
Ako presne funguje tá delegation? Teda, aké konkrétne privilégiá sa chystáš delegovať userovi?

---

_[zfs-manage-shell/zfs-manage-shell, line 9 [r2]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/10#-KDiDpIkkj82-SAUt_Lm:-KDiDpIkkj82-SAUt_Ln:-752588808) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/0895867ca3ccfeac9461fad696d6fd1a6b19374d/zfs-manage-shell/zfs-manage-shell#L9)):_
s/Read its man page/See zfs(8)/
(konvencia)

---

_[zfs-manage-shell/zfs-manage-shell, line 27 [r2]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/10#-KDiEWj08KMAi3l26V3q:-KDiEWj08KMAi3l26V3r:343756937) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/0895867ca3ccfeac9461fad696d6fd1a6b19374d/zfs-manage-shell/zfs-manage-shell#L27)):_
preformulovala by som na "Command to be executed. Omit to start interactive shell."

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/10#-:-KDiDe3LfZwYqslTFl_E:-2107977558)_

**Comment by lubo** [comment]
Suhlasim s Kamilou, `zfs-shell` by bol lepsi nazov.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/10#-:-KDiGYzTFyyokQ_u8apV:-1900246197)_

**Comment by adam-dej** [comment]
Will do.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_[a discussion](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/10#-KDiEyKgJhDdJzDTnPCY:-KDiG58P3-u3m0YZRjSk:-1330103736) (no related file):_
Niesom si istý či rozumiem, momentálny use-case je písať úplne rovnaké príkazy ako obvykle. `-c` je pre scripty čo chcú cez SSH iba jeden príkaz (like `ssh user@inteligent "zfs snapshot whatever@whatever"`)

---

_[a discussion](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/10#-KDiFFr_SEQQAL3YLrMe:-KDiG_zncdJnVlDBuabU:82646767) (no related file):_
Konkrétne privilégia budú `snapshot` a `rollback` a to iba na root dataset (a jeho potomkov) nejakého jailu. To im dovoli urobit snapshot a rollbacknut posledny snapshot.

---

_[zfs-manage-shell/zfs-manage-shell, line 9 [r2]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/10#-KDiDpIkkj82-SAUt_Lm:-KDiG3PZINGg2DyePTAa:-499146009) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/0895867ca3ccfeac9461fad696d6fd1a6b19374d/zfs-manage-shell/zfs-manage-shell#L9)):_
Done.

---

_[zfs-manage-shell/zfs-manage-shell, line 27 [r2]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/10#-KDiEWj08KMAi3l26V3q:-KDiG3DXnQPZfDispIX_:-499146009) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/0895867ca3ccfeac9461fad696d6fd1a6b19374d/zfs-manage-shell/zfs-manage-shell#L27)):_
Done.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/10#-:-KDiMaCnmcN4Xd3EVcol:1085483994)_

**Comment by AnotherKamila** [comment]
Reviewed 3 of 4 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[a discussion](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/10#-KDiEyKgJhDdJzDTnPCY:-KDiNK_CJZ4HR4EnnLGM:404505664) (no related file):_
Myslím že keď máš interaktívny shell, mohol by si písať iba `zfs-shell$ snapshot` as opposed to `zfs-shell$ zfs snapshot`, čím by si ušetril 4 keypresses / command. Ale v skutočnosti je mi to úplne jedno.

---

_[a discussion](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/10#-KDiFFr_SEQQAL3YLrMe:-KDiNmU0-tuCdiZpi3Bl:-821822812) (no related file):_
SG. List / čítať vedia všetci? A modifikovať properties nevedia, že?

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/10)_

**Comment by adam-dej** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[a discussion](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/10#-KDiFFr_SEQQAL3YLrMe:-KDiP9nVqM2hcXPqfukY:-1887955504) (no related file):_
Čítať vedia všetci, modifikovať properties nevedia (tested).

---

_[a discussion](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/10#-KDiEyKgJhDdJzDTnPCY:-KDiP_OOJCbxaTcjMgTp:1537218016) (no related file):_
To nechcem robiť. Duplicita kódu kôli podpore toho aj toho, a ak chceš priveľmi šetriť keypresses, má to tab completion, takže `z` `tab` `<space>` ti ušetrí jeden keypress...

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/10)_

**Comment by AnotherKamila** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[a discussion](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/10#-KDiFFr_SEQQAL3YLrMe:-KDiQB_aSIviOt_anxm8:1705999657) (no related file):_
Dobre.

---

_[a discussion](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/10#-KDiEyKgJhDdJzDTnPCY:-KDiQHsS6QsZpnPkeS2n:1915220744) (no related file):_
Uuuu, tab completion :D Hoci iba na command, nie na argumenty. Well, whatever :D

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/10)_

**Pull request merged**
