### PR TITLE
Create dirty-repo-shutup, fixes #15

### LINKED ISSUE #15: [repo-dirty-checker] Spísať `repo-dirty-shutup`
Tento script umlčí warningy o špinavom `/etc`, čas sa začne rátať od znovu

### PR DESCRIPTION
**Pull request by pepsin92**
This change is [Reviewable](https://reviewable.io/reviews/trojsten/sysadmin-script-collection/34)

### CODE REVIEW

**Comment by lubo** [comment]
Good job, but it seems like it'd be better to implement this feature in repo-dirty-checker istead. That approach would require no duplicate code.

**Comment by adam-dej** [comment]
I disagree. The duplicate code is unfortunate, but I don't want to launch a `repo-dirty-checker` binary to shut it up, mostly because by omiting a switch I can screw up the counter.

Although I would settle for a simple wrapper script `repo-dirty-shutup` which will call `repo-dirty-checker` with correct parameters.

Or have I misunderstood you?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/34#-:-KSmap9xtyM0nmYiLB0S:biheukw)_

**Comment by lubo** [comment]
You got it right. Having the wrapper would solve all the problems.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/34#-:-KSmcDN00YqyHbJHKBpz:b4d4gho)_

**Comment by pepsin92** [comment]
Closing so it doesn't glow in my PRs after 3 years

**Pull request closed without merging**
