### PR TITLE
Write `setup-log`

### PR DESCRIPTION
**Pull request by adam-dej**
This change is [Reviewable](https://reviewable.io/reviews/trojsten/sysadmin-script-collection/11)

### CODE REVIEW

**Comment by ivan-lattak** [comment]
@adam-dej ty si zobral moj predchadzajuci commit, ja som odvtedy mal dalsi, v utorok, bolo to spustitelne a otestovane, neviem, kde sa ten commit stratil

**Comment by adam-dej** [comment]
Eh, evidentne som nieco pokazil pri rebase. Vychadzal som z tvojho najposlednejsieho commitu (mal v message 'tested'), len som to presuval do vlastnej branche a vsetko...

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/11#-:-KDk50TXcM5P-CS0SO-U:-2124735202)_

**Comment by ivan-lattak** [comment]
potom dobre, je to commit 714b4fccb1c3e1e79f121e17c648a8b24ceaff1e, github taky nepozna, tak som bol zmateny

**Comment by lubo** [comment]
Preco `trojsten-log.conf` a nie `setup-log.conf` ? A este by som vec prehnal beautifierom.

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

_[setup-log/setup-log, line 12 [r3]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/11#-KDk7-pT9j0w65sej6fy:-KDk7-pT9j0w65sej6fz:-528005161) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/6b33ec66ddd33cbe79aa83004274ec82d80689d9/setup-log/setup-log#L12)):_
Potrebuje byt `config` loadnuty do globalneho scopu ? IMHO by bolo lepsie pre reusabilitu krmit kazdu funkciu na vstupe s tym co potrebuje.

---

_[setup-log/setup-log, line 62 [r3]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/11#-KDk07O39VGqqnramQgh:-KDk07O39VGqqnramQgi:-551225974) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/6b33ec66ddd33cbe79aa83004274ec82d80689d9/setup-log/setup-log#L62)):_
[configparser](https://docs.python.org/3.5/library/configparser.html) ? I ked nechceme `.ini`, mozno by to fungovalo s `.conf`.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/11#-:-KDk5ymdA83oHgY9lz5-:-532567350)_

**Comment by adam-dej** [comment]
Lebo tento config je specificky pre trojsten-style setup logy, aspon to bola povodna idea. Ale suhlasim ze `setup-log.conf` je lepsie meno.

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

_[setup-log/setup-log, line 12 [r3]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/11#-KDk7-pT9j0w65sej6fy:-KDm3hlrLrvxeLix87q-:-725171899) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/6b33ec66ddd33cbe79aa83004274ec82d80689d9/setup-log/setup-log#L12)):_
Config je jeden a globalny pre cely beh scriptu. Mas pravdu, ale nechcelo sa mi pisat skoro vsade argument naviac.

---

_[setup-log/setup-log, line 62 [r3]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/11#-KDk07O39VGqqnramQgh:-KDm3o8ofajphKo_8iVW:-1185898527) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/6b33ec66ddd33cbe79aa83004274ec82d80689d9/setup-log/setup-log#L62)):_
Ano, configparser by bol vzorak a ano, fungoval by, kedze syntax toho `.conf` suboru je ostrou podmnozinou syntaxu `.ini`. Prepises to prosim ak chces?

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/11#-:-KDm3xhIxX-5CesS7h02:-1325684003)_

**Comment by lubo** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

_[setup-log/setup-log, line 62 [r3]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/11#-KDk07O39VGqqnramQgh:-KDmcN54EsgbO5ZrEOad:-1046920433) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/6b33ec66ddd33cbe79aa83004274ec82d80689d9/setup-log/setup-log#L62)):_
Tak asi nefungovalo, dostavam MissingSectionHeaderError. [configobj](https://github.com/DiffSK/configobj) by mohlo byt to, co nam treba, ale chceme sem tahat libky tretich stran ?

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/11)_

**Comment by adam-dej** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

_[setup-log/setup-log, line 62 [r3]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/11#-KDk07O39VGqqnramQgh:-KDmd_JY2bRahPcFS6vw:-944176807) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/6b33ec66ddd33cbe79aa83004274ec82d80689d9/setup-log/setup-log#L62)):_
"Keys may (but need not) be grouped into arbitrarily named sections." Na druhu stranu, mal som si precitat python docs: "…implements a basic configuration language which provides a structure _similar_ to […] Microsoft Windows INI files".
Nie, libky tretich stran nechceme. Je na tebe ci sa rozhodnes pridat section header alebo nechas read config tak ako je.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/11)_

**Comment by lubo** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

_[setup-log/setup-log, line 62 [r3]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/11#-KDk07O39VGqqnramQgh:-KDnP-Y43v93B_tXG4mc:-1082904943) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/6b33ec66ddd33cbe79aa83004274ec82d80689d9/setup-log/setup-log#L62)):_
Okay, nechajme to teda pre teraz tak ako to je a riesme to ked nam sucasna implementacia prestane stacit.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/11)_

**Comment by lubo** [comment]
Reviewed 1 of 4 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/11)_

**Comment by adam-dej** [comment]
Este treba pockat kym sa @AnotherKamila vyjadri

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/11#-:-KDnbN3Z1WOSmExxyEAU:1751537004)_

**Comment by AnotherKamila** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

_[a discussion](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/11#-KDnnGy1JIZKbFpqeYjn:-KDnnGy2jyfjmAhAVu_8:-664621995) (no related file):_
Aj sme to poriadne vyskúšali pred tým, ako to pustíme na ostré súbory, že :D Nechce sa mi totiž rozmýšľať, či to funguje :D

---

_[README.md, line 47 [r4]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/11#-KDngSzNjH1Jcrco82rS:-KDngSzNjH1Jcrco82rT:398950846) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/c7d18051ca640f8b3eaec6cd3db67f5ddf4de1e5/README.md#L47)):_
To je hrozná veta :-D Konkrétne: "automated scripted" je nadbytočná redundancia; a príliš fancy. Preformulovala by som na "Automates adding messages to our setup logs."

---

_[setup-log/setup-log, line 22 [r4]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/11#-KDnhHBlJrW7oxYVG4eL:-KDnhHBmT4jgfMMB1AgJ:2082858183) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/c7d18051ca640f8b3eaec6cd3db67f5ddf4de1e5/setup-log/setup-log#L22)):_
80-char rule je užitočné iba ak je užitočné. Tu ani na podobných miestach nie je užitočné, lebo čítanie sťažuje miesto zjednodušovania. Povoľujem zlepiť na 1 riadok, ak autor chce.

---

_[setup-log/setup-log, line 38 [r4]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/11#-KDnhp_caL1McWn5u54D:-KDnhp_caL1McWn5u54E:-2107713702) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/c7d18051ca640f8b3eaec6cd3db67f5ddf4de1e5/setup-log/setup-log#L38)):_
A sme si istí, že toto na inom systéme ako mojom notebooku dáva správny formát? Preferovala by som explicitný format string, ak to je nutné pretláčať cez stringy.

---

_[setup-log/setup-log, line 68 [r4]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/11#-KDnjixTPJQX80aA0Wkf:-KDnjixTPJQX80aA0Wkg:121901102) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/c7d18051ca640f8b3eaec6cd3db67f5ddf4de1e5/setup-log/setup-log#L68)):_
Nemala by `line[0]` tiež byť stripped?

Napríklad možno by som nad tento riadok ešte prihodila `line[0], line[1] = line[0].strip(), line[1].strip()` (a následne pokojne zahodila henten prvý `line.strip()`) alebo whatever.

Blbá poznámka: možno napríklad pre toto by sme mohli chcieť configparser. Teraz sa toto asi už nikomu nechce oné, a v podstate whatever, ale vo všeobecnosti configparser považujem za dobrý nápad. Prípadne možno dopísať TODO?

---

_[setup-log/setup-log, line 99 [r4]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/11#-KDnmNPgrm4NN9M6SWuB:-KDnmNPhRAqkYQeX6vwF:392398910) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/c7d18051ca640f8b3eaec6cd3db67f5ddf4de1e5/setup-log/setup-log#L99)):_
Opäť pind na explicitný date format string.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/11)_

**Comment by AnotherKamila** [comment]
Reviewed 1 of 4 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/11)_

**Comment by adam-dej** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_[a discussion](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/11#-KDnnGy1JIZKbFpqeYjn:-KDnv1NhBtSv7rPDBnNL:-1314373068) (no related file):_
Pouzivam to uz cely den na virtualke, so far so good. Testovane aj s malformed logmi. Naviac, logy su pod gitom.

---

_[setup-log/setup-log, line 38 [r4]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/11#-KDnhp_caL1McWn5u54D:-KDnvVVT3XAV2MZyGNpp:689806922) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/c7d18051ca640f8b3eaec6cd3db67f5ddf4de1e5/setup-log/setup-log#L38)):_
Nie je nutne pretlacat cez stringy, viac by sa mi pacilo porovnanie objektu reprezentujuceho datum.

---

_[setup-log/setup-log, line 68 [r4]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/11#-KDnjixTPJQX80aA0Wkf:-KDnvfiq3b3brj-AQbnd:-1969535859) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/c7d18051ca640f8b3eaec6cd3db67f5ddf4de1e5/setup-log/setup-log#L68)):_
Suhlasim  dopisanim ako TODO. configparser sme  s Kucim riesili, neviem ci si citala...

---

_[setup-log/setup-log, line 99 [r4]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/11#-KDnmNPgrm4NN9M6SWuB:-KDnvnJPey9C4MpZ0QK7:160401764) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/c7d18051ca640f8b3eaec6cd3db67f5ddf4de1e5/setup-log/setup-log#L99)):_
ack

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/11)_

**Comment by AnotherKamila** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[setup-log/setup-log, line 68 [r4]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/11#-KDnjixTPJQX80aA0Wkf:-KDnyDU9ZsGu23J1XgmM:-863797171) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/c7d18051ca640f8b3eaec6cd3db67f5ddf4de1e5/setup-log/setup-log#L68)):_
Čítala a som spokojná s "niekedy", ale zároveň som chcela dať najavo, že configparser _je_ dobrý nápad.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/11)_

**Comment by lubo** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

_[setup-log/setup-log, line 38 [r4]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/11#-KDnhp_caL1McWn5u54D:-KDoK3rhffebV36HEKSi:2093973867) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/c7d18051ca640f8b3eaec6cd3db67f5ddf4de1e5/setup-log/setup-log#L38)):_
Chceme niekde porovnavat datumy ?

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/11)_

**Comment by adam-dej** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

_[setup-log/setup-log, line 38 [r4]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/11#-KDnhp_caL1McWn5u54D:-KDoKsiAXlR0d5EgKMNa:689821714) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/c7d18051ca640f8b3eaec6cd3db67f5ddf4de1e5/setup-log/setup-log#L38)):_
Err, zly line. L99. Sorry

---

_[setup-log/setup-log, line 99 [r5]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/11#-KDoLCN5eZVnuuayRW3c:-KDoLCN5eZVnuuayRW3d:1103920100) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/69eb6dfb55f1665513fa256499aed6040fc925ab/setup-log/setup-log#L99)):_
Nie je dobre pretlacat cez stringy, viac by sa mi pacilo porovnanie objektu reprezentujuceho datum.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/11)_

**Comment by lubo** [comment]
1579977cdc84b953877e9a05c0b059e547f6a090, ktory si vyziadal @adam-dej, som pridal sem, nakolko nemame cas na dalsi PR.

---

Reviewed 1 of 2 files at r5.
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/11#-:-KDokM1GEekTlp7So6kq:-1013814460)_

**Comment by lubo** [comment]
Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/11)_

**Pull request merged**
