### PR TITLE
Add style guide

### PR DESCRIPTION
**Pull request by adam-dej**
This change is [Reviewable](https://reviewable.io/reviews/trojsten/sysadmin-script-collection/9)

### CODE REVIEW

**Comment by lubo** [comment]
Obsahovo to vyzera dobre, nespominam si na ziadne dalsie vynimky. Este nech sa na to pozrie @AnotherKamila .

---

Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

_[README.md, line 9 [r1]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/9#-KD7hlHiCU1tSFOMNYFh:-KD7hlHiCU1tSFOMNYFi:-111104503) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/d831298302fcec823f08e0a76f27bbd3748e1908/README.md#L9)):_
`We are adhering` - na co ten present continuous ? Toto si ziada present simple.

---

_[README.md, line 10 [r1]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/9#-KD7iCxNMAWdXgFzHrWI:-KD7iCxNMAWdXgFzHrWJ:593095262) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/d831298302fcec823f08e0a76f27bbd3748e1908/README.md#L10)):_
Podobne ako vyssie.

---

_[README.md, line 12 [r1]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/9#-KD7iGNiLxoprLO5uUbQ:-KD7iGNiLxoprLO5uUbR:-462192267) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/d831298302fcec823f08e0a76f27bbd3748e1908/README.md#L12)):_
A zas. Tu by sme mozno aj chceli povedat, ze skripty by _mali_ pouzivat taby (konzistentnost, Makefile compatibility, ...).

---

_[README.md, line 19 [r1]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/9#-KD7iViWqrAUfgNlxVYG:-KD7iViWqrAUfgNlxVYH:-552745672) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/d831298302fcec823f08e0a76f27bbd3748e1908/README.md#L19)):_
A zas ten p. continuous.

---

_[README.md, line 21 [r1]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/9#-KD7lqpbnOETFeqw98ac:-KD7lqpdlqKp8zrPipqf:927357524) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/d831298302fcec823f08e0a76f27bbd3748e1908/README.md#L21)):_
A este jeden. Tu by som mozno aj zmenil stavbu vety, `We prefer Python 3 where possible.` mi znie anglickejsie.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/9#-:-KD7iaT1KT3zDAU__gCq:-72194902)_

**Comment by AnotherKamila** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

_[README.md, line 9 [r1]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/9#-KD7hlHiCU1tSFOMNYFh:-KD7wTNseQeTdZKxIipg:1675029023) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/d831298302fcec823f08e0a76f27bbd3748e1908/README.md#L9)):_
Veru tak -- "we adhere". Also: s/those/these/.

A keď už pindám, Style Guide zvyknú byť 2 slová.

---

_[README.md, line 10 [r1]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/9#-KD7iCxNMAWdXgFzHrWI:-KD7wlFFNcaBsz9rremv:964692089) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/d831298302fcec823f08e0a76f27bbd3748e1908/README.md#L10)):_
Povedať explicitne, že `sh`, nemôže zaškodiť. Prípadne s nejakým linkom na bashizmy (@adam-dej nejaký spomínal).

---

_[README.md, line 11 [r1]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/9#-KD7x2ZZ0144zagvmStg:-KD7x2ZZ0144zagvmSth:-1969375423) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/d831298302fcec823f08e0a76f27bbd3748e1908/README.md#L11)):_
Doplnila by som: ale zato máme radi slovo `readonly`.

---

_[README.md, line 37 [r1]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/9#-KD7xbV-sU2O6shXNHg3:-KD7xbV-sU2O6shXNHg4:845548842) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/d831298302fcec823f08e0a76f27bbd3748e1908/README.md#L37)):_
Unrelated, ale... `repo-dirty-checker` bude zjavne mať spoločný kód s `properly`. Ale v podstate keďže je to v princípe `cd $dir && git status`, je mi to dostatočne jedno.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/9)_

**Comment by lubo** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

_[README.md, line 11 [r1]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/9#-KD7x2ZZ0144zagvmStg:-KD7zVGQAap3zf3FQbIw:1528529665) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/d831298302fcec823f08e0a76f27bbd3748e1908/README.md#L11)):_
Mozno by sme rovno mohli doplnit link na zoznam features podporovanych POSIX shellom. Niekde som ho videl, ale uz neviem kde. Ak by ho niekto nasiel, tak by bolo skvele.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/9)_

**Comment by adam-dej** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[README.md, line 10 [r1]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/9#-KD7iCxNMAWdXgFzHrWI:-KDD5ZosZbeb6icIv32b:1389362468) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/d831298302fcec823f08e0a76f27bbd3748e1908/README.md#L10)):_
Link na bashizmy mozno ani netreba, existuje shellcheck.

---

_[README.md, line 11 [r1]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/9#-KD7x2ZZ0144zagvmStg:-KDD64IESP9dw14GKe6v:484943541) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/d831298302fcec823f08e0a76f27bbd3748e1908/README.md#L11)):_
Neviem ho najst. Nestaci ked vypinda shellcheck?

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/9)_

**Comment by lubo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

_[README.md, line 9 [r1]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/9#-KD7hlHiCU1tSFOMNYFh:-KDDGLW-9-ZyEfbW8K6c:1330173136) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/d831298302fcec823f08e0a76f27bbd3748e1908/README.md#L9)):_
Ano, daj tam Style Guide. Do textu linku by bolo pekne zahrnut aj slovo Google a `with the following exceptions` by znelo lepsie.

---

_[README.md, line 10 [r1]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/9#-KD7iCxNMAWdXgFzHrWI:-KDDFQqu1u3r6XEhC8sc:-594892341) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/d831298302fcec823f08e0a76f27bbd3748e1908/README.md#L10)):_
ShellCheck (vid. moj dalsi comment). Anyway, `s/those/these/` alebo `s/those/the/`.

---

_[README.md, line 11 [r1]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/9#-KD7x2ZZ0144zagvmStg:-KDDCDMO9H7-1zPi4kUc:-307278098) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/d831298302fcec823f08e0a76f27bbd3748e1908/README.md#L11)):_
Vies co, kaslime na linky. Myslim, ze nikto z nas nema cas to hladat a nie to este citat. ShellCheck.

---

_[README.md, line 15 [r2]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/9#-KDDGx88Vuf36KTiObvT:-KDDGx88Vuf36KTiObvU:997264983) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/46ad085ba9d79df2573685250b03556958925b18/README.md#L15)):_
`s/those/the/` a `s/shellcheck/ShellCheck`.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/9)_

**Comment by adam-dej** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

_[README.md, line 9 [r1]](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/9#-KD7hlHiCU1tSFOMNYFh:-KDD_ukD2-ynvtDCnIDT:-1852271398) ([raw file](https://github.com/trojsten/sysadmin-script-collection/blob/d831298302fcec823f08e0a76f27bbd3748e1908/README.md#L9)):_
Ahaa, na ten nadpis ste to mysleli... Kedze ste nedali koment k tomu nadpisu, nevedel som na co sa vztahuje, a predpokladal som ze v linku maju byt iba dve slova. Fixed.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/9)_

**Comment by lubo** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/9#-:-KDKJgNUbnkw9pjvGvCN:1417088721)_

**Comment by lubo** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/9)_

**Pull request merged**
