### PR TITLE
Add snapless option to properly, fixes #30

### LINKED ISSUE #30: [properly] Snapshot je niekedy overkill
Niekedy je overkill robit snapshot. Preto by to chcelo switch ktory skippne robenie snapshotu.

### PR DESCRIPTION
**Pull request by pepsin92**
This change is [Reviewable](https://reviewable.io/reviews/trojsten/sysadmin-script-collection/33)

### CODE REVIEW

**Comment by adam-dej** [comment]
Please run the script against `shellcheck`, there are some issues that need to be fixed. Also try running in under some POSIX-compliant shell please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/33#-:-KTFLdORgxC1ZbqY5MDb:b-uh5grn)_

**Comment by lubo** [comment]
What about setting up Code Climate for this repo ? It supports both pep8 and ShellCheck. I could do that.

**Comment by adam-dej** [comment]
We can give it a try. Please set it up.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/trojsten/sysadmin-script-collection/33#-:-KTJ24a0yiGejGdIS65r:bpwi093)_

**Comment by pepsin92** [comment]
Closing so it doesn't glow in my PRs after 3 years

**Pull request closed without merging**
